---
galaxy_info:
  role_name: hostname
  author: koyashiro
  description: Configure system hostname for Debian
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - debian
    - hostname

dependencies: []
