---
galaxy_info:
  role_name: editor
  author: koyashiro
  description: Configure default editor for Debian
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - debian
    - editor

dependencies: []
