---
galaxy_info:
  role_name: packages
  author: koyashiro
  description: Install common packages for Debian
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - debian
    - packages

dependencies: []
