---
galaxy_info:
  role_name: timezone
  author: koyashiro
  description: Configure system timezone for Debian
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - debian
    - timezone

dependencies: []
